name: hrms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.9.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.4
  data_table_2: ^2.6.0
  excel: ^4.0.6
  file_saver: ^0.3.1
  email_validator: ^3.0.0
  pdf: ^3.11.3
  responsive_framework: ^1.5.1
  syncfusion_flutter_datagrid: ^30.2.7
  fl_chart: ^1.0.0
  pie_chart: ^5.3.2
  printing: ^5.12.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  rxdart: ^0.28.0
  get: ^4.7.2
  loading_animation_widget: ^1.3.0
  http: ^1.4.0
  file_picker: ^10.2.0
  open_file: ^3.5.10
  syncfusion_flutter_charts: ^30.1.39
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.0
  flutter_boxicons: ^3.2.0
  enefty_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  cross_file: ^0.3.4+2
  internet_connection_checker: ^3.0.1
  typed_data: ^1.4.0
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
#  awesome_notifications: ^0.10.1
  pie_chart_sz: 1.1.1
  animated_text_kit: ^4.2.3
  flutter_skeleton_ui: ^0.0.6
  get_storage: ^2.1.1
  flutter_local_notifications: ^19.5.0
  win_toast: ^0.4.0
  awesome_snackbar_content: ^0.1.8
  pretty_animated_text: ^2.0.0
  flutter_calendar_carousel: ^2.5.4
  table_calendar: ^3.2.0
  device_preview: ^1.3.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/deamlogo.png
    - assets/images/unavailabledata.png
    - assets/images/profileuser.png
    - assets/images/setting_icons.png
    - assets/images/nodata.png
    - assets/images/otp.png
    - assets/images/total-employee.png
    - assets/images/leaverequest.png
    - assets/images/department.png
    - assets/images/available.png
    - assets/images/supabase.png
    - assets/images/email_verify.png
    - assets/images/otpforgot.png
    - assets/images/forgotscreen.png
    - assets/icon/logout.png
    - assets/icon/logouts.png
    - assets/icon/calendar.png
    - assets/icon/calendars.png
    - assets/icon/equilibrium.png
    - assets/images/changepass.png
    - assets/icon/happy.png
    - assets/icon/hospital.png
    - assets/icon/school.png
    - assets/icon/wallet.png
    - assets/icon/folder.png
    - assets/icon/user.png
    - assets/icon/key.png
    - assets/icon/overview.png
    - assets/icon/setting.png
    - assets/icon/usersetup.png
    - assets/icon/userupdate.png
    - assets/icon/policy.png
    - assets/icon/manageuser.png
    - assets/icon/manageteam.png
    - assets/icon/usergroup.png
    - assets/icon/userabsent.png
    - assets/icon/userlate.png
    - assets/icon/home.png
    - assets/icon/usercheckin.png
    - assets/icon/userleave.png
    - assets/icon/notification.png
    - assets/icon/log-out.png
    - assets/images/team_banner.jpg

    #    - assets/sound/default_notification_send.wav
    - .env
    - assets/Fonts/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # hrms:
  fonts:
    - family: 7TH.ttf
      fonts:
        - asset: assets/Fonts/7TH.ttf
    - family: DODG5.ttf
      fonts:
        - asset: assets/Fonts/DODG5.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
